apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: env-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: env-creds
  data:
    - secretKey: mongodb_url
      remoteRef:
        key: vino-prod-env-creds
        property: mongodb_url
    - secretKey: mongodb_username
      remoteRef:
        key: vino-prod-env-creds
        property: mongodb_username
    - secretKey: mongodb_password
      remoteRef:
        key: vino-prod-env-creds
        property: mongodb_password
    - secretKey: database_url
      remoteRef:
        key: vino-prod-env-creds
        property: database_url
    - secretKey: database_username
      remoteRef:
        key: vino-prod-env-creds
        property: database_username
    - secretKey: database_password
      remoteRef:
        key: vino-prod-env-creds
        property: database_password

# DELETE_IF: cookiecutter.gen_k8s_yaml != 'yes'