resources:
- ../../base

namespace: default

secretGenerator:
  - name: env-creds
    envs:
      - everyone_knows.env

images:
  - name: ghcr.io/vino9org/vino-java-base/vino-demo-svc
    newName: sloppycoder/vino-demo-svc

# DELETE_IF: cookiecutter.gen_k8s_yaml != 'yes'