apiVersion: apps/v1
kind: Deployment
metadata:
  name: vino-demo-svc
  labels:
    app: vino-demo-svc
    version: v1
spec:
  selector:
    matchLabels:
      app: vino-demo-svc
      version: v1
  template:
    metadata:
      labels:
        app: vino-demo-svc
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: vino-demo-svc
        image: ghcr.io/vino9org/vino-java-base/vino-demo-svc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        # CC: {% if cookiecutter.database_type == 'mongodb' -%}
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: env-creds
              key: mongodb_url
        - name: SPRING_DATA_MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-creds
              key: mongodb_username
        - name: SPRING_DATA_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-creds
              key: mongodb_password
        # CC: {% endif -%}
        # CC: {% if cookiecutter.database_type == 'postgresql' or cookiecutter.database_type == 'mysql' -%}
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: env-creds
              key: database_url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-creds
              key: database_username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-creds
              key: database_password
        # CC: {% endif -%}
        - name: LOGGING_LEVEL_ROOT
          value: "WARN"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: vino-demo-svc
  labels:
    app: vino-demo-svc
    service: vino-demo-svc
spec:
  type: ClusterIP
  selector:
    app: vino-demo-svc
  ports:
  - name: http
    port: 8080
    targetPort: 8080

# DELETE_IF: cookiecutter.gen_k8s_yaml != 'yes'