# check document for more details:
# https://jqassistant.github.io/jqassistant/doc/1.12.2/manual/#core:Configuration
#
# this file is a place holder with only basic scan setting for using a local database
# and a proper project specific configuration and rules should be used

jqassistant:
  skip: false

#  scan result by default goes to a local embedded neo4j instance, which is good for local inspection
#  to centralized analysis, uncomment the following to send scan results to a remote database
#  store:
#    uri: neo4j://localhost
#    remote:
#      username: neo4j
#      password: password

  scan:
    reset: false
    continue-on-error: false

  analyze:
    group:
      - SprintBoot-Default
    rule:
      directory: jqassistant/
      default-concept-severity: MINOR
      default-constraint-severity: MAJOR
