apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: vino-demo-svc

build:
  artifacts:
  - image: sloppycoder/vino-demo-svc
    jib:
      args:
      - -DskipTests

manifests:
  kustomize:
    paths:
    - k8s/envs/dev

# DELETE_IF: cookiecutter.gen_k8s_yaml != 'yes'