on:
  push:
    branches:
      - main
      - develop
      - feature/*

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test
        run: mvn -B test

      - name: Build and deploy artifacts
        run: mvn -B -s settings.xml deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/vino9org/vino-java-base
        if: contains(fromJSON('["refs/heads/main", "refs/heads/master","refs/heads/develop"]'), github.ref)
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param: [vino-base-pom, vino-bom, vino-baselib, vino-svc-parent]
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: vino9org
          package-name: net.vino9.vino.${{ matrix.param }}
          package-type: maven
          min-versions-to-keep: 5
          token: ${{ secrets.GITHUB_TOKEN }}
