on:
  push:
    branches:
      - develop
      - main
      - feature/*

  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  build-n-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3

      - name: Build and test
        run: |
          ./gradlew -b test

      - name: Copy JaCoCo Report for publishing
        run: |
          for module in "vino-base-lib vino-demosvc"; do
              if [ -f "$module/build/reports/jacoco/test/index.html" ]; then
                  rm -rf coverage-reports/$module
                  cp -r $module/build/reports/jacoco/test coverage-reports/$module
                  echo copied jacoco report for $module
              else
                  echo jacoco report not found for $module
              fi
          done

      - name: Upload JaCoCo Report to GitHub Pages
        if: startsWith(github.ref, 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-reports
        continue-on-error: true

      - name: Build and deploy artifacts
        if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop'))
        run: |
          ./gradlew -b build deploy -x test\
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: build-n-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop'))
    strategy:
      matrix:
        param:
          - vino-base-pom
          - vino-bom
          - vino-baselib
          - vino-svc-parent
    steps:
      - id: clean-up
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner}}
          package-name: net.vino9.vino.${{ matrix.param }}
          package-type: maven
          min-versions-to-keep: 10
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
