on:
  push:
    branches:
      - main
      - develop
      - feature/*

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      build_type: ${{ steps.envs.outputs.build_type }}

    steps:
      - name: Setup ENVs for use later
        id: envs
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || \
                "${{ github.ref }}" == "refs/heads/develop" ]]; then
             echo "build_type=full" >> $GITHUB_OUTPUT
           else
             echo "build_type=verify" >> $GITHUB_OUTPUT
           fi

      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test
        run: |
          ./mvnw --batch-mode verify

      - name: Copy JaCoCo Report for publishing
        run: |
          if [ -d "vino-baselib/target/site/jacoco" ]; then
            cp -r vino-baselib/target/site/jacoco coverage-reports/vino-baselib
          fi

          if [ -d "vino-demo-svc/target/site/jacoco" ]; then
            cp -r vino-demo-svc/target/site/jacoco coverage-reports/vino-demo-svc
          fi

      - name: Upload JaCoCo Report to GitHub Pages
        if: steps.envs.outputs.build_type == 'full'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-reports

      - name: Build and deploy artifacts
        if: steps.envs.outputs.build_type == 'full'
        run: |
          ./mvnw --batch-mode -s settings.xml deploy \
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.build_type == 'full'
    strategy:
      matrix:
        param:
          - vino-base-pom
          - vino-bom
          - vino-baselib
          - vino-svc-parent
    steps:
      - id: clean-up
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner}}
          package-name: net.vino9.vino.${{ matrix.param }}
          package-type: maven
          min-versions-to-keep: 10
          token: ${{ secrets.GITHUB_TOKEN }}
